name: SwagLabs Selenium Automation

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@latest-version

    - name: Set up JDK
      uses: actions/setup-java@latest-version
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Build with Maven
      run: mvn clean test